---
title: "Week 2 lecture"
author: "Jessica Widyawati"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```

#read stocks data
```{r}
stocks = readRDS("../data/wk2_stocks.rds")

```

```{r}
#cumulative returns of the SP stocks
sum(stocks$SPY_returns)*100

#average daily returns of the SP index
sum(stocks$SPY_returns)/(sum(!duplicated(stocks$date)))

mean(stocks$SPY_returns)*100

#standard deviation
sd(stocks$SPY_returns)*100

```
+ The cumulative returns of the S&P index during this period is `sum(stocks$SPY_returns)*100`

+ The average daily returns of the S&P index during this period is `mean(stocks$SPY_returns)*100`

+ The standard deviation of the daily returns of the S&P index during this period is `sd(stocks$SPY_returns)*100`

plots
```{r}
#prices of SP
stocks %>% 
  ggplot(aes(x = date, y = SPY_prices)) +
  geom_line()

#total yearly returns of SP from 2001 to 2023
stocks %>% 
  mutate(year = year(date))%>%
  group_by(year) %>%
  summarise(yearly_total = sum(SPY_returns)) %>%
  ggplot(aes(x= year, y = yearly_total)) +
  geom_col()
```